# Generated by Django 2.2 on 2019-04-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='happyhour',
            name='bonus',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
