# Generated by Django 2.2.6 on 2019-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20190707_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='end_time',
        ),
        migrations.AddField(
            model_name='lap',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
