# Generated by Django 2.2.6 on 2019-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20191005_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
