# Generated by Django 2.2.6 on 2019-10-15 18:27

from django.db import migrations, models
import django.db.models.deletion
import re
import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20191008_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=5)),
                ('id_example', models.CharField(max_length=8)),
                ('id_regex', regex_field.fields.RegexField(max_length=128, verbose_name=re.RegexFlag(2))),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='speedy_team',
        ),
        migrations.AddField(
            model_name='runner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.Group'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='identification',
            field=models.CharField(max_length=8),
        ),
    ]
