# Generated by Django 2.2.6 on 2019-10-15 18:32

from django.db import migrations
import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_auto_20191015_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='university',
            name='id_regex',
            field=regex_field.fields.RegexField(max_length=128),
        ),
    ]
