# Generated by Django 2.2.6 on 2019-10-16 05:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_auto_20191015_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='id_regex',
        ),
        migrations.AlterField(
            model_name='runner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.Group'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='identification',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{0,8}$', 'This is not a valid university identification number.')]),
        ),
    ]
