# Generated by Django 2.2.6 on 2019-10-20 15:23

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_remove_group_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupscore',
            name='group',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competition.Group'),
        ),
    ]
